# Import all important liberaries

In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
import pandas as pd 

In [4]:
import seaborn as sns

# Import dataset

In [54]:
 from sklearn.datasets import load_breast_cancer

In [6]:
data = load_breast_cancer()

In [7]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [8]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [9]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [10]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [11]:
df=pd.DataFrame(np.c_[data.data, data.target], columns=[list(data.feature_names)+['Target']])

In [12]:
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   

  worst symmetry worst fractal dimension Target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  

[5 rows x 31 columns]

In [13]:
df.shape

(569, 31)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   (mean radius,)              569 non-null    float64
 1   (mean texture,)             569 non-null    float64
 2   (mean perimeter,)           569 non-null    float64
 3   (mean area,)                569 non-null    float64
 4   (mean smoothness,)          569 non-null    float64
 5   (mean compactness,)         569 non-null    float64
 6   (mean concavity,)           569 non-null    float64
 7   (mean concave points,)      569 non-null    float64
 8   (mean symmetry,)            569 non-null    float64
 9   (mean fractal dimension,)   569 non-null    float64
 10  (radius error,)             569 non-null    float64
 11  (texture error,)            569 non-null    float64
 12  (perimeter error,)          569 non-null    float64
 13  (area error,)               569 non

In [15]:
X=df.drop('Target', axis=1)
X.head()

C:\Users\pc\anaconda3\lib\site-packages\pandas\core\generic.py:4153: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst radius worst texture worst perimeter  \
0                0.07871  ...        25.38         17.33          184.60   
1                0.05667  ...        24.99         23.41          158.80   
2                0.05999  ...        23.57         25.53          152.50   
3                0.09744  ...        14.91         26.50           98.87   
4                0.05883  ...        22.54         16.67          152.20   

  worst area worst smoothness worst compactness worst concavity  \
0     2019.0           0.1622            0.6656          0.7119   
1     1956.0           0.1238            0.1866          0.2416   
2     1709.0           0.1444            0.4245          0.4504   
3      567.7           0.2098            0.8663          0.6869   
4     1575.0           0.1374            0.2050          0.4000   

  worst concave points worst symmetry worst fractal dimension  
0               0.2654         0.4601                 0.11890  
1               0.1860         0.2750                 0.08902  
2               0.2430         0.3613                 0.08758  
3               0.2575         0.6638                 0.17300  
4               0.1625         0.2364                 0.07678  

[5 rows x 30 columns]

In [16]:
y=df['Target']
y.tail()

Target
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=2020)

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
DTC=DecisionTreeClassifier(criterion='gini')

In [21]:
DTC.fit(X_train,y_train)

DecisionTreeClassifier()

In [22]:
DTC.score(X_test,y_test)

0.9414893617021277

In [23]:
y_pred=DTC.predict(X_test)

In [24]:
y_test

Target
236    0.0
106    1.0
284    1.0
262    0.0
356    1.0
..     ...
545    1.0
227    1.0
107    1.0
388    1.0
213    0.0

[188 rows x 1 columns]

In [25]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [26]:
print('Accuracy score is:',accuracy_score(y_test, y_pred)*100)

Accuracy score is: 94.14893617021278


In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.92      0.94      0.93        78
         1.0       0.95      0.95      0.95       110

    accuracy                           0.94       188
   macro avg       0.94      0.94      0.94       188
weighted avg       0.94      0.94      0.94       188



In [35]:
cm=confusion_matrix

In [36]:
cm(y_pred,y_test )

array([[ 73,   6],
       [  5, 104]], dtype=int64)

In [49]:
patient1=[X_test.iloc[-1,:].values]

In [50]:
patient1


[array([1.742e+01, 2.556e+01, 1.145e+02, 9.480e+02, 1.006e-01, 1.146e-01,
        1.682e-01, 6.597e-02, 1.308e-01, 5.866e-02, 5.296e-01, 1.667e+00,
        3.767e+00, 5.853e+01, 3.113e-02, 8.555e-02, 1.438e-01, 3.927e-02,
        2.175e-02, 1.256e-02, 1.807e+01, 2.807e+01, 1.204e+02, 1.021e+03,
        1.243e-01, 1.793e-01, 2.803e-01, 1.099e-01, 1.603e-01, 6.818e-02])]

In [51]:
DTC.predict(patient1)

array([0.])

In [52]:
y_test.iloc[-1,:]

Target    0.0
Name: 213, dtype: float64

In [53]:
if DTC.predict(patient1)[0]==0:
    print('Patient has Cancer(Malignant Tumor)')
else:
    print('Patient has No Cancer(benign Tumor)')

Patient has Cancer(Malignant Tumor)
